### PR TITLE
Fixed grammatical errors and changed certain words/phrases for clarity & consistency

### PR DESCRIPTION
**Pull request by roman-au**
## Changes

- Modified the wording of a sentence in [custom-thumbnails.md](https://github.com/Roblox/creator-docs/commit/861d718decc385a972e873de85a87e38ba6a367a) for clarity.
- Added punctuation and improved sentence structure in [intellectual-property.md](https://github.com/Roblox/creator-docs/commit/5d7511538e3111521e365f86029d56cde9381a93).
- Fixed typos, added punctuation and improved sentence structure in [marketplace-policy.md](https://github.com/Roblox/creator-docs/commit/954b87c4b02266c6b42d5ef7ae4109778d36b864).
- Fixed grammatical errors, added punctuation and improved sentence structure in [publishing-to-marketplace.md](https://github.com/Roblox/creator-docs/commit/5d3c85651fc42a3a25c2b0d8da29505adb398099).

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by roman-au** [comment]
Tried to open separate PRs for each category, but I'm unable to open more than one per repository and any changes I make will push to the pending PR I already have open. May have to fork multiple times to do this in future. 😅

**Comment by tchu-roblox** [comment]
> Tried to open separate PRs for each category, but I'm unable to open more than one per repository and any changes I make will push to the pending PR I already have open. May have to fork multiple times to do this in future. 😅

Hi @roman-au, you can only have one pull request open for each branch on your fork. You can make more branches on your fork to create more pull requests. See the [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) and the video in the [README](https://github.com/Roblox/creator-docs#readme) 🙂

**Comment by roman-au** [comment]
Still waiting on this to be merged. 😅

**Review by haan-roblox — APPROVED** [review]
Great catches @roman-au! Changes LGTM. Thanks again for taking the time to improve the docs.

**Comment by haan-roblox** [comment]
> Still waiting on this to be merged. 😅

Apologies! The team's a bit busy prepping for RDC. Hopefully we'll get these reviewed a bit quicker moving forward.

**Pull request merged**
