### PR TITLE
ATI67831 pályája

### PR DESCRIPTION
**Pull request by ATI67831**
## Checks

By submitting your pull request for review, you agree to the following:

- [ ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [ ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [ ] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by ATI67831** [comment]
H67zjhgbj

**Comment by ATI67831** [comment]
Ma

**Comment by ATI67831** [comment]
Ma

**Comment by NeonBlox** [comment]
**

> Your request has been Denied.

**

**Comment by NeonBlox** [comment]
Hi @ATI67831, thanks so much for helping improve the Roblox creator documentation! Our technical writing team will review your pull request soon. In the meantime, please ensure you've read through the [README.md](https://github.com/Roblox/creator-docs#readme), contribution guidelines, and [style recommendations](https://github.com/Roblox/creator-docs/blob/main/STYLE.md).

**Pull request closed without merging**
