### PR TITLE
Update tag-table.md

### PR DESCRIPTION
**Pull request by Ramdoys**
## Changes

Made some typo fixes for micro profiler tags, as well as adding the full sequence to some of them.

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by Rajihr2** [comment]
Hi

**Comment by Ramdoys** [comment]
@IgnisRBX Hey, I don't know if you have any control over this, but do you know if there is a possibility of better documentation on these tags. I could add more of course, but I wouldn't know what they do internally. Seems more like a Roblox Staff oriented thing.

**Review by aetter — APPROVED** [review]

**Comment by aetter** [comment]
Hey @Ramdoys, this looks great, thanks a bunch. We're always happy to add to the list, but we're trying to be selective about it since so there are a) so many b) many are tiny and c) many aren't actionable. Are there any in particular that you'd like to see?

**Comment by Ramdoys** [comment]
> Hey @Ramdoys, this looks great, thanks a bunch. We're always happy to add to the list, but we're trying to be selective about it since so there are a) so many b) many are tiny and c) many aren't actionable. Are there any in particular that you'd like to see?

@aetter Yeah, it totally makes sense for them to not be _all_ documented and that some don't have a major impact or can't be acted upon. As for ones I'd like to see, the following have definitely been ones I've been curious about:

- Prepare/UpdatePrepare/updateDynamicParts
- Prepare/UpdatePrepare/processPendingParts
- RenderJob/TransferControlToRenderThread/WaitForRenderThread
- Simulation/physicsSteppedTotal/physicsStepped/frameStep ( - just in general, it has a ton of tags under it usually)
- Perform/Scene/UpdateView

Thanks!

**Comment by aetter** [comment]
> > Hey @Ramdoys, this looks great, thanks a bunch. We're always happy to add to the list, but we're trying to be selective about it since so there are a) so many b) many are tiny and c) many aren't actionable. Are there any in particular that you'd like to see?
> 
> @aetter Yeah, it totally makes sense for them to not be _all_ documented and that some don't have a major impact or can't be acted upon. As for ones I'd like to see, the following have definitely been ones I've been curious about:
> 
> * Prepare/UpdatePrepare/updateDynamicParts
> * Prepare/UpdatePrepare/processPendingParts
> * RenderJob/TransferControlToRenderThread/WaitForRenderThread
> * Simulation/physicsSteppedTotal/physicsStepped/frameStep ( - just in general, it has a ton of tags under it usually)
> * Perform/Scene/UpdateView
> 
> Thanks!

Huge thanks, I've reported an (internal) bug on myself and will check these out in the coming weeks.

**Review by CEO-jun — COMMENTED** [review]
Ramdoys:tag-table-patch-1

**Comment by CEO-jun** [comment]
CEO-jun

**Pull request merged**
