### PR TITLE
Update index.md82

### PR DESCRIPTION
**Pull request by 15marten**
This is it I'm lol

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by 15marten** [comment]
Omg

**Comment by 15marten** [comment]
This is helpful

**Comment by 15marten** [comment]
Nice

**Comment by 15marten** [comment]
**hwi**

**Comment by IgnisRBX** [comment]
We'd like to keep the breadcrumbs showing for this page, but thanks regardless.

**Pull request closed without merging**
