### PR TITLE
SelectionCollisionGroup note for collisions.md

### PR DESCRIPTION
**Pull request by stravant**
## Changes

Add note about new `StudioSelectable` convention in Collisions documentation. (Target release date: Feb 22nd)

### CODE REVIEW

**Comment by Naruto23581** [comment]
Espero les guste

**Comment by Naruto23581** [comment]
Good

**Comment by Naruto23581** [comment]
Good

**Comment by Naruto23581** [comment]
Good

**Comment by Naruto23581** [comment]
Xd

**Comment by omaromx** [comment]
wow

**Comment by omaromx** [comment]
Wow

**Comment by Aydencoeurdegaide** [comment]
Retrouve sur YouTube les nouvelles version ancienne https//:youtube.com//:aydencoeurdefeu

**Comment by Aydencoeurdegaide** [comment]
> ``

**Comment by Aydencoeurdegaide** [comment]
[](url)

**Pull request closed without merging**
