### PR TITLE
Rename content/en-us/studio/index.md to content/en-us/689doh

### PR DESCRIPTION
**Pull request by 689doh**
=)

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by 689doh** [comment]
...

**Comment by 689doh** [comment]
...

**Comment by 689doh** [comment]
Leave

**Comment by WaviestBalloon** [comment]
Are you okay?

**Pull request closed without merging**
