### PR TITLE
Update TextService.yaml

### PR DESCRIPTION
**Pull request by LordMerc**
Removed Instance from FilterStringAsync method and replaced with TextFilterResult as return type

## Changes
Replaced return type of FilterStringAsync method with TextFilterResult 

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

### CODE REVIEW

**Comment by LordMerc** [comment]
Need this to be reviewed already

**Comment by IgnisRBX** [comment]
GitHub is reporting no changes for this PR.

**Comment by LordMerc** [comment]
> GitHub is reporting no changes for this PR.

You sure? It's showing the changes for me.

**Comment by LordMerc** [comment]
image
I'm seeing what I forked is updated, but ig the review never went thru?

**Comment by IgnisRBX** [comment]
Hmmm, maybe it was changed somewhere previously in the stream? Does the current description match what you wanted it to say?
https://create.roblox.com/docs/reference/engine/classes/TextService#FilterStringAsync

If not, could you please open a new PR with the desired change? Then I can process that and close this one...

**Comment by LordMerc** [comment]
> Hmmm, maybe it was changed somewhere previously in the stream? Does the current description match what you wanted it to say? https://create.roblox.com/docs/reference/engine/classes/TextService#FilterStringAsync
> 
> If not, could you please open a new PR with the desired change? Then I can process that and close this one...

Aye the description matches up. The only pull change was changing the return type from Instance to TextFilterResult.

**Pull request closed without merging**
